language: java
jdk:
  - oraclejdk8

os:
  - linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: bintray
  file: "bintray.json"
  user: "eoQBprRMu6h3FxCl6XXJyn0JS3lk6q/lejUOluxAwvigSd3BeX9x9+csdMqFxKb+g4EU8etjZ1j/iPI7WzqLuxImOz34Q6zMWS+J4eEUZtENoASmdae6clrhWbrJTHin7vbzfLQgOmE0SCW+MZ7VoSWHqK2Ml/d4ZtNCPPDeiBF1VYyIdTxY+htZAIwnVRGse5uKmNJnrvN27RJT7uO/ySnpg93rq5xhyuEdZf3/OSv+qMBzjqLkw0raGaKf9Zs6OaG/8CcGtS633aRcWB/UI8qOpQ4TmdCeVyBbgEwlk7mqKwcb5zFIO1aHIKkoTV76xnHNCfbNiWQNJr46xmc2giQwKGoq6CleroCkHLtOj+Y+mD+1vxTurUEE+qAd5ECvT56M+6csgmxltHWlBm8NR44iY3blx4ifp6w8c/HdJxh2TURShcO5surOM63qX6la9VxJOZJ9Op9aIhLPH+fRfziUfp6sOKgQh7SIza8vd/UlnlvllYG8ZfDOBaQIDfWJbKCIstrBkQ2RJ0TiYrCC9av7GQeC5JApeNdBkVzVNcHH5+IEoPsz703c94mPvL+JdHm5/nfJBziQ9UKOJ4n3ffEif/vArKNOyxeQnbzmKqqF4FcwArLyWoFgNhLpNxFbyIk2Zu9LP8UtL5Hm39llCoBRsTTc5dNxSSImbndwPHA="
  key: "kqkoFd/NDXcP6nYmVcwrfb79f2xIguqvfujpvPJsovFMZCaS+ybDC9PMZKSB19kQMiV7P78d7eIVfuasM3laGackgHqK2Os3tgxbl2Q20XovK+++JbwKa64R18pp1KuUcSrwuHvjAoic+Dxd78wKeNcNpYer+JzBSpgU9WfgRucTY5EqALwd1c6NPDe5iXTJLSfrK0sLDBuU7foruB2X0c2SzvPrC0Vy7GeoQFoz5wVnp1ZjoPLII9+LmCB8N9cgftVW4C2QnR3R1L8t/p1r0nganxeOyj6D6pXmMCWLrU/DaeZYqbblyM42VNA5W/SPntfHCt4QxME/MjyRDuhM3xXFdHySOt9kCHmuRJHm5bcHVQwnobHfe2YSujfbA79XGU2BxVIzeKgI35PJijAtTRy1TdzDezyKCUb78tgpMffyN8VNsBRKtQRCORr6Msf815Zl9Z//EKbebnAH9DNe+tdsYoi0m4dQiuvHgz44wcPulCu0JrBFlKCK5E7g8FZXM4BKpxBCKoFYhDWb8yRLlkA6xRcq0jHxodIixjQwqqXEX8lo19hsBIpav1piQ6j40govx6mxbxoufYk6i8d09Rp/1/vvRygfwiCMJML82t75LxO68hmAaeEqo2+jkyJhz86drE4l2vzZGfduFWzVmQy7IS/owVop4iAA5dG/mw0="
  skip_cleanup: true # to upload artifacts created during the build